### ISSUE TITLE
Upgrade to Gatsby v2

### ISSUE THREAD

**Issue by sheelah** [reactdenver/reactdenver.com#10]
It'd be worth upgrading to Gatsby v2 to take advantage of its faster build times etc.  At the same time, we'd upgrade all other gatsby-* packages being used to their v2 equivalents.

Migration guide:
https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/

**Comment by dgarwood** [comment]
@sheelah isn't this a duplicate of #1 ?

**Comment by sheelah** [comment]
@dgarwood Yes! I missed that one.  Closing in favor of #1.
