### ISSUE TITLE
Investigate Meetup API for pulling in events

### ISSUE THREAD

**Issue by sheelah** [reactdenver/reactdenver.com#11]
It'd be nice if events could be pulled in directly from meetup:
https://www.meetup.com/meetup_api/docs/

There'd need to be a job to automatically rebuild the site though (daily, like in a cron job) so that new events would show up on the site.

If the long-term plan is not to use meetup though, then this probably wouldn't be worth pursuing.

**Comment by mckernanin** [comment]
We're working on a new version of the site built with gatsby v2. This issue has been addressed in the new repo, which can be found here: https://github.com/reactdenver/react-denver-v2

We do still need to figure out rebuilds, based on meetup updates (documented here: https://github.com/reactdenver/react-denver-v2/issues/5)
