### ISSUE TITLE
Move to single lock file (yarn vs npm)

### ISSUE THREAD

**Issue by sheelah** [reactdenver/reactdenver.com#12]
Noticed this repo has both a `yarn.lock` and `package-lock.json` file.  How about standardizing on one or the other (seems the preference is for yarn, looking at the README), and removing the other from source control?

![screenshot from 2018-11-15 13-23-09](https://user-images.githubusercontent.com/1900318/48579417-a47cf500-e8d9-11e8-8991-eddd0ac11651.png)

**Comment by mckernanin** [comment]
We're working on a new version of the site built with gatsby v2. This issue has been addressed in the new repo, which can be found here: https://github.com/reactdenver/react-denver-v2
