### ISSUE TITLE
Start script fails to build website 

### ISSUE THREAD

**Issue by mfazza** [reactdenver/reactdenver.com#25]
Anyone else getting this when building it through "npm start"?  If this does work for anyone, feel free to close this issue, and I'll investigate it further on my end.  Otherwise, I'll post findings here.  I quickly went through some issues on Github and it seemed to be related to a gatsby quirk that was later fixed, but I wanted to make sure someone else was also getting this.

error UNHANDLED REJECTION

  TypeError: Cannot read property 'internal' of undefined
  - schema.js:612 _.flatMap.groupBy.node
    [reactdenver.com]/[gatsby]/dist/schema/schema.js:612:102
  - lodash.js:497 arrayAggregator
    [reactdenver.com]/[lodash]/lodash.js:497:34
  - lodash.js:4829 Function.groupBy
    [reactdenver.com]/[lodash]/lodash.js:4829:16
  - lodash.js:4374 
    [reactdenver.com]/[lodash]/lodash.js:4374:28
  - lodash.js:683 arrayReduce
    [reactdenver.com]/[lodash]/lodash.js:683:21
  - lodash.js:4373 baseWrapperValue
    [reactdenver.com]/[lodash]/lodash.js:4373:14
  - lodash.js:9052 LodashWrapper.wrapperValue
    [reactdenver.com]/[lodash]/lodash.js:9052:14
  - schema.js:612 groupChildNodesByType
    [reactdenver.com]/[gatsby]/dist/schema/schema.js:612:145
  - schema.js:545 addConvenienceChildrenFields
    [reactdenver.com]/[gatsby]/dist/schema/schema.js:545:28
  - schema.js:192 
    [reactdenver.com]/[gatsby]/dist/schema/schema.js:192:13
  
  - Generator.next
  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-denver-website@2.0.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-denver-website@2.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MattFazza/.npm/_logs/2019-04-26T22_41_49_445Z-debug.log

**Comment by mckernanin** [comment]
I’ll check it out. What node version are you using?

**Comment by mfazza** [comment]
My latest stable version is 10.13.0.  I'm updating the LTS and seeing if it works.  Worth mentioning that 12.0.0 also didn't work.

**Comment by mfazza** [comment]
Update: I had a problem with my installation of node, and I was able to fix it by doing a complete clean/reinstall.  It works for me now with both the LTS (10.15.3) and the latest (12.0.0).  Turns out it was on my end.  My bad!
