### ISSUE TITLE
Create root route, headers and content containers

### ISSUE THREAD

**Issue by JeffBaumgardt** [reactdenver/reactdenver.com#30]
![Image](https://user-images.githubusercontent.com/777527/188530809-234ddc0b-6c47-4ae6-ad37-4038a08d6d99.png)

https://www.figma.com/file/gM0ZHdtJ6dqcwf4zGKbT5o/React-Denver?node-id=48%3A665

**Comment by danielwlemmon** [comment]
@JeffBaumgardt  I'm about done with the styling for the top section header and the area selected in this image.  I need the discord invite link.  For now I just put a link to Discord's website.  
Also, the events route is not working for some reason.  Do you want me to see if I can fix it before doing the pull request for this issue?

**Comment by JeffBaumgardt** [comment]
Here's the discord link - https://discord.gg/fFngBEwNmV

Don't worry about the events route. Just make the link to it and we'll address the route in a next step.
