### ISSUE TITLE
Light Mode Dark Mode Toggle button

### ISSUE THREAD

**Issue by rahulpandey70** [reactdenver/reactdenver.com#64]
Issue with light and dark mode toggle button, design doesn't look much promising and when dark mode is enable button text isn't much readable.

![image](https://github.com/reactdenver/reactdenver.com/assets/34403988/58eee365-d1b5-442e-aa49-2e70fd25bde1)

**Comment by JeffBaumgardt** [comment]
Looks like a simple class change on theme change. I'll take a gander at it in the morning.

Thanks for the feedback and screenshot.

**Comment by rahulpandey70** [comment]
Yes just adding a simple css property, Or you can make icon clickable that will look much clean, and also move it at the top right or bottom right. Just a suggestion.

**Comment by JeffBaumgardt** [comment]
I addressed this in 1bb710be2891bd9dc8540d54712df834082d2bf4 on the next.js branch. I had some other work that needed to be committed as well. So it was bundled.
