### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by sheelah** [reactdenver/reactdenver.com#9]
Adding this so we can come up with a prioritized list of tasks to make the UI better.  Here's what I'm seeing so far:

- [ ] (mobile) Ensure homepage's event items don't break out of the grid
- [x] (mobile) Re-collapse the nav once a page is selected
- [ ] (mobile) Reduce the homepage's `h1` font size & line height 
- [x] Add a favicon
- [ ] Decide whether to hide the homepage's intro blurb on other pages (I think it can be left out) so that it's only shown in one place
- [ ] Decide whether to hide placeholder pages in the nav until they have actual page content.  Showing only the key pages in the nav would also be a better desktop experience.
- [ ] Decide whether to keep the CO state flag (doesn't really serve any purpose, right?). Can we show a mini version of the React Denver logo instead?
- [ ] Add pagination for the homepage's events list
- [ ] Add a site-wide footer (could link to the code of conduct along with social links  -- Twitter, YouTube, Meetup)

**Comment by sheelah** [comment]
@willklein @mckernanin Ready for some feedback on this initial list, so that I have an idea of what tasks would be most valuable right now. Any other ideas? Let me know who else we should include in this discussion.

**Comment by willklein** [comment]
@sheelah this is great. I agree with everything you have there. Thank you!

**Comment by sheelah** [comment]
Got a PR out for the 2nd item. If I should assign a specific reviewer for PRs, let me know @willklein.

**Comment by mckernanin** [comment]
We're working on a new version of the site built with gatsby v2. The new repo can be found here: https://github.com/reactdenver/react-denver-v2

I'll recreate the action items here that can be addressed on the new site, as issues on the new repo.
